name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Cypress
        run: npx cypress install

      # - name: Run Cypress tests and record
      #   env:
      #     CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      #   run: npm run cy:run

      - name: Generate Mochawesome report (optional)
        if: success() || failure()
        run: |
          npx mochawesome-merge cypress/results/*.json > cypress/results/report.json
          npx marge cypress/results/report.json --reportDir cypress/results/report
