name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Install Cypress
        run: npx cypress install
      
      - name: Install Allure CLI + allure-cypress
        if: always()
        run: npm install -g allure-commandline allure-cypress

      - name: Run Cypress tests
        run: npx cypress run --browser chrome --headless

      - name: Find allure results
        run: |
          echo "Searching for allure-results..."
          find . -type d -name "allure-results" || echo "'allure-results' is not found"


      - name: Setup Java for Allure
        if: always()
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 25



      - name: Generate Allure Report
        if: always()
        run: allure generate allure-results --clean -o allure-report

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          
      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos/

      - name: Upload Cypress screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots/
